"""Service Desk State Definition - Central TypedDict for LangGraph orchestration."""

from datetime import datetime
from typing import Annotated, Literal, Optional, TypedDict

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


def append_to_list(current: list, update: list) -> list:
    """Reducer that appends elements to an existing list."""
    if current is None:
        current = []
    if update is None:
        update = []
    return current + update


class EmailComponents(TypedDict, total=False):
    """Parsed email components (for future phases)."""

    sender: str
    sender_name: str
    sender_domain: str
    subject: str
    body: str
    signature: Optional[str]
    attachments: list[str]
    received_at: str


class CallerInfo(TypedDict, total=False):
    """Validated caller information (for future phases)."""

    is_authorized: bool
    caller_id: str
    company: str
    authorization_schedule: str
    validation_timestamp: str


class BankInfo(TypedDict, total=False):
    """Bank identification information (for future phases)."""

    is_bank_related: bool
    bank_name: Optional[str]
    identified_by: Optional[str]
    confidence_score: float


class ProblemClassification(TypedDict, total=False):
    """Problem classification details (for future phases)."""

    category: str
    subcategory: Optional[str]
    priority: str
    confidence_score: float
    matched_keywords: list[str]


class TicketInfo(TypedDict, total=False):
    """Created ticket information (for future phases)."""

    ticket_id: Optional[str]
    jira_key: Optional[str]
    status: str
    created_at: Optional[str]
    assignee: Optional[str]


class ServiceDeskState(TypedDict, total=False):
    """Main Service Desk state.

    This TypedDict defines all information flowing through the agent graph.
    Each field has a specific purpose and some use custom reducers for
    concurrent updates.

    MVP Fields (Active):
        messages: Conversation history
        current_input: Current user input
        classification: Identified request type
        response: Generated response
        next_agent: Next agent to execute

    Future Phase Fields (Stubs):
        email_components: Parsed email data
        caller_info: Validated caller info
        bank_info: Bank identification data
        problem_classification: Category classification
        ticket_info: Jira ticket data
    """

    # === MVP FIELDS (Active) ===

    # Message history with add_messages reducer for deduplication
    messages: Annotated[list[BaseMessage], add_messages]

    # Current user input (raw text)
    current_input: str

    # Router classification: what type of request
    classification: Literal[
        "it_support",
        "billing",
        "general_inquiry",
        "escalation",
        "unknown",
    ]

    # Detailed sub-classification (optional)
    sub_classification: Optional[str]

    # Response generated by specialized agent
    response: str

    # Next agent to execute (for routing)
    next_agent: Optional[str]

    # Human escalation flag
    needs_human_escalation: bool

    # Escalation reason (if applicable)
    escalation_reason: Optional[str]

    # History of executed agents (for debugging/tracing)
    agent_trace: Annotated[list[str], append_to_list]

    # Errors encountered during processing
    errors: Annotated[list[str], append_to_list]

    # Session metadata
    session_id: str
    timestamp: str

    # Classification confidence score
    confidence_score: float

    # === FUTURE PHASE FIELDS (Stubs) ===

    # Phase 2: Email parsing
    email_components: Optional[EmailComponents]

    # Phase 3: Caller validation
    caller_info: Optional[CallerInfo]

    # Phase 4: Bank identification
    bank_info: Optional[BankInfo]

    # Phase 5: XLS classification
    problem_classification: Optional[ProblemClassification]

    # Phase 6: Jira integration
    ticket_info: Optional[TicketInfo]

    # Phase 7: Auto-reply
    auto_reply_sent: bool
    auto_reply_content: Optional[str]


def create_initial_state(
    user_input: str,
    session_id: str,
) -> ServiceDeskState:
    """Create initial state for a new request.

    Args:
        user_input: The user's input message.
        session_id: Unique session identifier.

    Returns:
        Initial ServiceDeskState with default values.
    """
    return ServiceDeskState(
        messages=[],
        current_input=user_input,
        classification="unknown",
        sub_classification=None,
        response="",
        next_agent=None,
        needs_human_escalation=False,
        escalation_reason=None,
        agent_trace=[],
        errors=[],
        session_id=session_id,
        timestamp=datetime.now().isoformat(),
        confidence_score=0.0,
        email_components=None,
        caller_info=None,
        bank_info=None,
        problem_classification=None,
        ticket_info=None,
        auto_reply_sent=False,
        auto_reply_content=None,
    )
